### ISSUE TITLE
composer install not working

### ISSUE THREAD

**Issue by Arikowid31** [fikrisuheri/laravel-toko-online-anime-store#3]
PS C:\laragon\www\laravel-toko-online-anime-store> composer install
You are running Composer with SSL/TLS protection disabled.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - nette/schema is locked to version v1.2.2 and an update of this package was not requested.
    - nette/schema v1.2.2 requires php >=7.1 <8.2 -> your php version (8.2.2) does not satisfy that requirement.
  Problem 2
    - nette/utils is locked to version v3.2.7 and an update of this package was not requested.
    - nette/utils v3.2.7 requires php >=7.2 <8.2 -> your php version (8.2.2) does not satisfy that requirement.
  Problem 3
    - phpspec/prophecy is locked to version v1.15.0 and an update of this package was not requested.
    - phpspec/prophecy v1.15.0 requires php ^7.2 || ~8.0, <8.2 -> your php version (8.2.2) does not satisfy that requirement.
  Problem 4
    - nette/schema v1.2.2 requires php >=7.1 <8.2 -> your php version (8.2.2) does not satisfy that requirement.
    - league/config v1.1.1 requires nette/schema ^1.2 -> satisfiable by nette/schema[v1.2.2].
    - league/config is locked to version v1.1.1 and an update of this package was not requested.

**Comment by Faqih0776** [comment]
coba pakai php 7 kak
